import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { useTheme } from "../hooks/useTheme";
import NotificationBell from "@/components/NotificationBell";
import { useAuth } from "@/context/authContext";
const Navbar = () => {
    const { theme, toggleTheme } = useTheme();
    const { user, logout } = useAuth();
    return (_jsx("nav", { className: "bg-primary text-white shadow-card dark:bg-neutral-dark dark:text-neutral-light transition-colors duration-300", children: _jsxs("div", { className: "container mx-auto px-4 py-3 flex justify-between items-center", children: [_jsx(Link, { to: "/", className: "font-display text-2xl font-semibold tracking-tight", children: "ServiGo" }), _jsxs("ul", { className: "flex gap-6 items-center", children: [_jsx("li", { children: _jsx(Link, { to: "/", className: "hover:text-secondary transition", children: "Inicio" }) }), _jsx("li", { children: _jsx(Link, { to: "/servicios", className: "hover:text-secondary transition", children: "Servicios" }) }), _jsx("li", { children: _jsx(Link, { to: "/contacto", className: "hover:text-secondary transition", children: "Contacto" }) }), user && (_jsx("li", { children: _jsx(NotificationBell, {}) })), _jsx("li", { children: _jsx("button", { onClick: toggleTheme, className: "ml-4 text-lg bg-secondary px-3 py-1 rounded-full text-neutral-dark hover:opacity-80 transition", title: "Cambiar tema", children: theme === "light" ? "🌙" : "☀️" }) }), user ? (_jsxs(_Fragment, { children: [_jsxs("li", { className: "text-sm font-semibold", children: ["Hola, ", user.name.split(" ")[0], " \uD83D\uDC4B"] }), _jsx("li", { children: _jsx("button", { onClick: logout, className: "bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded-full text-sm font-semibold transition", children: "Cerrar sesi\u00F3n" }) })] })) : (_jsxs(_Fragment, { children: [_jsx("li", { children: _jsx(Link, { to: "/login", className: "bg-secondary text-neutral-dark px-3 py-1 rounded-full font-semibold hover:opacity-80 transition", children: "Login" }) }), _jsx("li", { children: _jsx(Link, { to: "/register", className: "border border-secondary px-3 py-1 rounded-full font-semibold hover:bg-secondary hover:text-neutral-dark transition", children: "Registro" }) }), _jsx("li", { children: _jsx(Link, { to: "/notificaciones", className: "hover:text-secondary transition", children: "Historial" }) }), _jsx("li", { children: _jsx(Link, { to: "/chat", className: "hover:text-secondary transition", children: "Chat" }) })] }))] })] }) }));
};
export default Navbar;
